# Generated by Django 4.0.3 on 2022-04-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
